image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - chmod +x ./gradlew
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  tags:
   - dalfcs_gitlab_docker_ci

  script:
    - chmod +x ./gradlew
    - ./gradlew check
deploy:
  stage: deploy
  tags:
     - dalfcs_gitlab_docker_ci
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/group-24-test-server.git || true
    - git push -f heroku HEAD:master
  only:
    - develop